backoffice/urls.py
from django.urls import path

from backoffice.views import *

app_name = 'bo'
urlpatterns = [
    path('', Index.as_view(), name='index'),

    path('animal/list/', AnimalList.as_view(), name='animal_list'),
    path('animal/add/', AnimalAdd.as_view(), name='animal_add'),
    path('animal/edit/<int:pk>/', AnimalEdit.as_view(), name='animal_edit'),
    path('animal/delete/<int:pk>/', AnimalDelete.as_view(), name='animal_delete'),
    path('animal/detail/<int:pk>/', AnimalDetail.as_view(), name='animal_detail'),

    path('diagnostico/list/', DiagnosticoList.as_view(), name='diagnostico_list'),
    path('diagnostico/add/', DiagnosticoAdd.as_view(), name='diagnostico_add'),
    path('diagnostico/edit/<int:pk>/', DiagnosticoEdit.as_view(), name='diagnostico_edit'),
    path('diagnostico/delete/<int:pk>/', DiagnosticoDelete.as_view(), name='diagnostico_delete'),
    path('diagnostico/detail/<int:pk>/', DiagnosticoDetail.as_view(), name='diagnostico_detail'),

    path('historial/list/', HistorialList.as_view(), name='historial_list'),
    path('historial/add/', HistorialAdd.as_view(), name='historial_add'),
    path('historial/edit/<int:pk>/', HistorialEdit.as_view(), name='historial_edit'),
    path('historial/delete/<int:pk>/', HistorialDelete.as_view(), name='historial_delete'),
    path('historial/detail/<int:pk>/', HistorialDetail.as_view(), name='historial_detail'),

    path('paciente/list/', PacienteList.as_view(), name='paciente_list'),
    path('paciente/add/', PacienteAdd.as_view(), name='paciente_add'),
    path('paciente/edit/<int:pk>/', PacienteEdit.as_view(), name='paciente_edit'),
    path('paciente/delete/<int:pk>/', PacienteDelete.as_view(), name='paciente_delete'),
    path('paciente/detail/<int:pk>/', PacienteDetail.as_view(), name='paciente_detail'),

    path('raza/list/', RazaList.as_view(), name='raza_list'),
    path('raza/add/', RazaAdd.as_view(), name='raza_add'),
    path('raza/edit/<int:pk>/', RazaEdit.as_view(), name='raza_edit'),
    path('raza/delete/<int:pk>/', RazaDelete.as_view(), name='raza_delete'),
    path('raza/detail/<int:pk>/', RazaDetail.as_view(), name='raza_detail'),

    path('api/v1/animal/', ApiAnimalList.as_view()),
    path('api/v1/diagnostico/', ApiDiagnosticoList.as_view()),
    path('api/v1/historial/', ApiHistorialList.as_view()),
    path('api/v1/paciente/', ApiPacienteList.as_view()),
    path('api/v1/raza/', ApiRazaList.as_view()),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

petproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backoffice.urls')),

]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Historial Veterinario</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'bo:index' %}">Company name</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Busca..." aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Bienvenido {{ user }}</a>
        </li>
    </ul>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'bo:logout' %}">Cerrar sesión</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'bo:index' %}">
                            <span data-feather="home"></span>
                            Inicio <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bo:animal_list' %}">
                            <span data-feather="github"></span>
                            Animales
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bo:raza_list' %}">
                            <span data-feather="gitlab"></span>
                            Razas
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bo:diagnostico_list' %}">
                            <span data-feather="clipboard"></span>
                            Diagnósticos
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bo:paciente_list' %}">
                            <span data-feather="clock"></span>
                            Pacientes
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bo:historial_list' %}">
                            <span data-feather="layers"></span>
                            Historiales
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% block main %}
            {% endblock main %}
        </main>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>
</body>
</html>